###
POST http://localhost:8000/new-ticket HTTP/1.1
content-type: application/json

# TODO : keypairs and choices should be a single map, not a list of maps.
# same with choices.
{
    "comment":"asassa",
    "formFields": {
        "loca": "RA-N1-O-165",
        "type": "printer"
    },
    "formCheckBoxes": {
        "app.form.checkboxes.paper-jam": false,
        "app.form.checkboxes.no-paper": true,
        "app.form.checkboxes.toner": true,
        "app.form.checkboxes.other": false
    },
    "contactEmail": "blablabla",
    "type": "SPACESHIP"
}

